'use client';
import { Roboto } from 'next/font/google';
import Modal from './components/Modal';

const inter = Roboto({ subsets: ['latin'], weight: '500' });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function Practice2Layout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
